In [1]:
import numpy
import pandas

In [2]:
melt_depth = numpy.loadtxt('Depths_Replicate', delimiter = ' | ')
powers = numpy.loadtxt('Powers_Replicate', delimiter = ' | ')
speeds = numpy.loadtxt('Speeds_Replicate', delimiter = ' | ')
Tmax = numpy.loadtxt('TMax_Replicate', delimiter = ' | ')

In [3]:
pandas.DataFrame(melt_depth, columns = numpy.ndarray.tolist(speeds), index = numpy.ndarray.tolist(powers))

1.8   1.5   1.2   0.8   0.5
400.0  47.2  52.6  59.9  75.1  95.5
300.0  39.4  44.1  50.3  63.7  82.0
200.0  29.8  33.6  39.0  49.7  64.8
150.0  24.1  27.4  31.8  41.2  54.1

In [12]:
pandas.DataFrame(Tmax, columns = numpy.ndarray.tolist(speeds), index = numpy.ndarray.tolist(powers))

1.8           1.5           1.2           0.8           0.5
400.0  17444.213692  18882.268915  20762.674316  24480.002387  29176.084842
300.0  13158.160269  14236.701686  15647.005737  18435.001791  21957.063631
200.0   8872.106846   9591.134457  10531.337158  12390.001194  14738.042421
150.0   6729.080135   7268.350843   7973.502869   9367.500895  11128.531816

In [4]:
MD_flat = melt_depth.flatten()

In [5]:
MD_this = numpy.array([47.2, 52.6, 59.9, 39.4, 44.1, 50.3, 63.7, 33.6, 39.0, 49.7, 64.8, 31.8, 41.2, 54.1])
MD_this

array([47.2, 52.6, 59.9, 39.4, 44.1, 50.3, 63.7, 33.6, 39. , 49.7, 64.8,
       31.8, 41.2, 54.1])

In [6]:
numpy.shape(MD_this)

(14,)

In [7]:
MD_kamath = numpy.array( [ 50.4, 57.6, 62.4, 43.2, 48.0, 55.2, 67.2, 38.4, 43.2, 52.8, 67.2, 36.0, 43.2, 55.2])

In [8]:
numpy.shape(MD_kamath)

(14,)

In [9]:
 (MD_kamath-MD_this)

array([3.2, 5. , 2.5, 3.8, 3.9, 4.9, 3.5, 4.8, 4.2, 3.1, 2.4, 4.2, 2. ,
       1.1])

In [10]:
numpy.around(( (MD_kamath-MD_this)/ MD_this ) * 100, 1)

array([ 6.8,  9.5,  4.2,  9.6,  8.8,  9.7,  5.5, 14.3, 10.8,  6.2,  3.7,
       13.2,  4.9,  2. ])

In [11]:
numpy.around(( (MD_kamath-MD_this)/ MD_this ) * 100, 0)

array([ 7., 10.,  4., 10.,  9., 10.,  5., 14., 11.,  6.,  4., 13.,  5.,
        2.])